# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
import numpy as np
a = np.arange(10)
b =a.reshape(2,5)
print('1D array  = {0}'.format(a))
print('2D array  = {0}'.format(b))

1D array  = [0 1 2 3 4 5 6 7 8 9]
2D array  = [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [24]:
a=np.arange(10).reshape(2,5)
b=np.ones((2,5),dtype =np.int)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [26]:
a=np.arange(10).reshape(2,5)
b=np.ones((2,5),dtype =np.int)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [27]:
a= np.arange(10).reshape(2,5)
print(a)
a.flatten()

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [28]:
x = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,114]])
print (x)


TypeError: array() takes from 1 to 2 positional arguments but 3 were given

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

## Question:7

### Create 5x5 an array and find the square of an array?

## Question:8

### Create 5x6 an array and find the mean?

## Question:9

### Find the standard deviation of the previous array in Q8?

## Question:10

### Find the median of the previous array in Q8?

## Question:11

### Find the transpose of the previous array in Q8?

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

## Question:13

### Find the determinant of the previous array in Q12?

## Question:14

### Find the 5th and 95th percentile of an array?

## Question:15

### How to find if a given array has any null values?